version: '3.1'
services:
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
        - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: bitnami/kafka:latest
    container_name: 'kafka'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - "kafka_data:/bitnami"
    depends_on:
      - zookeeper

  producer:
    build: ./producer
    environment:
      KAFKA_BROKER: "kafka:9092"
      KAFKA_TOPIC: "coinbase"
      NODE_ENV: "production"
      PRODUCTS: "ETH-USD,BTC-USD"
    depends_on:
      - kafka

  # consumer:
  #   build: ./consumer
  #   environment:
  #     KAFKA_BROKER: "kafka1:9092"
  #     KAFKA_TOPIC: "coinbase"
  #   depends_on:
  #     - kafka1
  #     - producer

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local