version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.11-1.1.1
    ports:
      - "9092:9092"
    links:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: ${HOST_IP}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_CREATE_TOPICS: "topic-test:1:1"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # producer:
  #   build: ./producer
  #   environment:
  #     KAFKA_BROKER: "kafka:9092"
  #     KAFKA_TOPIC: "coinbase"
  #     NODE_ENV: "production"
  #     PRODUCTS: "ETH-USD,BTC-USD"
  #   depends_on:
  #     - kafka

  # consumer:
  #   build: ./consumer
  #   environment:
  #     KAFKA_BROKER: "kafka1:9092"
  #     KAFKA_TOPIC: "coinbase"
  #   depends_on:
  #     - kafka1
  #     - producer
